### ISSUE TITLE
Document Python coding guidelines to include isort

### ISSUE THREAD

**Issue by Cronus1007** [creativecommons/creativecommons.github.io-source#604]
## Problem
An addition to #276 by @TimidRobot where the Pyton coding guidelines lacks a litlle bit 
   - reduces efficiency of communication and pull requests
   - sets new contributors up to fail
   - increases cognitive work of working across multiple repositories
## Solution
- [x] Draft guidelines
## Additional context
- Isort

## Resources 
As mentioned by @TimidRobot in the linked PR above . 

> ## Resources
> Thank you @zackkrida for these!
> 
> * Avoiding language like "simply|just|easy" per [Don't use the word 'simply'](https://jameshfisher.com/2017/02/22/dont-use-simply/)
> * Consider items in [Writing style guide - The MDN project | MDN](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Writing_style_guide)
> * [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) (CC BY 3.0)
> * [Code Style — The Hitchhiker's Guide to Python](https://docs.python-guide.org/writing/style/) (CC BY-NC-SA 3.0)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by TimidRobot** [comment]
There's a good `isort` config in creativecommons/cc-licenses:[`pyproject.toml`](https://github.com/creativecommons/cc-licenses/blob/main/pyproject.toml):
```toml
[tool.isort]
import_heading_firstparty = 'First-party/Local'
import_heading_future = 'Future'
import_heading_stdlib = 'Standard library'
import_heading_thirdparty = 'Third-party'
line_length = 79
multi_line_output = 3
no_lines_before = 'LOCALFOLDER'
profile = 'black'
```

Personally, I find labeling the imports helps me track down issues much faster (ex. reduces confusion between 'Third-party' and 'First-party/Local').
